maintainer        "Ralph Rooding"
maintainer_email  "ralph@ralphrooding.com"
license           "MIT"
description       "Configure workstation apps and utilities"
long_description  "Configure workstation apps and utilities"
version           "1.0.0"
supports          "mac_os_x"
