maintainer        "Ralph Rooding"
maintainer_email  "ralph@ralphrooding.com"
license           "MIT"
description       "Configure workstation settings"
long_description  "Configure workstation settings"
version           "1.0.0"
supports          "mac_os_x"
